# Generated by Django 4.2.2 on 2023-11-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_email', models.EmailField(max_length=254)),
                ('admin_password', models.CharField(max_length=255)),
                ('admin_name', models.CharField(max_length=255)),
            ],
        ),
    ]
