# Generated by Django 4.2.2 on 2023-12-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eve_image',
            field=models.ImageField(upload_to='eve_images'),
        ),
    ]
